// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$ipndEf/1p9jdMYbdUWDDrOF1LRVlvxI3tRErZYb5tQzjG2YUPOUyC",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$eWJKQBW5QfPnc8JsxDl9k.aQAetORxOMGEsaNdyrRzzzKhcTnvJSO",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "DevOps Engineer",
                            Email = "pooja.ghosh@xyz.com",
                            FirstName = "Pooja",
                            JoinDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Ghosh",
                            Phone = "9876543201",
                            Salary = 980000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Supply Chain Analyst",
                            Email = "amit.joshi@xyz.com",
                            FirstName = "Amit",
                            JoinDate = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Joshi",
                            Phone = "9876543202",
                            Salary = 720000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Brand Manager",
                            Email = "lakshmi.chandran@xyz.com",
                            FirstName = "Lakshmi",
                            JoinDate = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Chandran",
                            Phone = "9876543203",
                            Salary = 840000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Tax Consultant",
                            Email = "suresh.babu@xyz.com",
                            FirstName = "Suresh",
                            JoinDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Babu",
                            Phone = "9876543204",
                            Salary = 910000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "QA Engineer",
                            Email = "meera.krishnan@xyz.com",
                            FirstName = "Meera",
                            JoinDate = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Krishnan",
                            Phone = "9876543205",
                            Salary = 690000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "rohan.kapoor@xyz.com",
                            FirstName = "Rohan",
                            JoinDate = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kapoor",
                            Phone = "9876543206",
                            Salary = 830000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "ananya.sen@xyz.com",
                            FirstName = "Ananya",
                            JoinDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Sen",
                            Phone = "9876543207",
                            Salary = 620000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Accounts Manager",
                            Email = "karthik.iyer@xyz.com",
                            FirstName = "Karthik",
                            JoinDate = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Iyer",
                            Phone = "9876543208",
                            Salary = 990000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "SEO Specialist",
                            Email = "nisha.verma@xyz.com",
                            FirstName = "Nisha",
                            JoinDate = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Verma",
                            Phone = "9876543209",
                            Salary = 570000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Logistics Manager",
                            Email = "harish.naidu@xyz.com",
                            FirstName = "Harish",
                            JoinDate = new DateTime(2025, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Naidu",
                            Phone = "9876543210",
                            Salary = 810000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "Talent Partner",
                            Email = "ritika.sharma@xyz.com",
                            FirstName = "Ritika",
                            JoinDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Sharma",
                            Phone = "9876543211",
                            Salary = 760000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Backend Developer",
                            Email = "vikas.nair@xyz.com",
                            FirstName = "Vikas",
                            JoinDate = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Nair",
                            Phone = "9876543212",
                            Salary = 1040000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Content Strategist",
                            Email = "sneha.kulkarni@xyz.com",
                            FirstName = "Sneha",
                            JoinDate = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kulkarni",
                            Phone = "9876543213",
                            Salary = 680000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Process Lead",
                            Email = "prakash.yadav@xyz.com",
                            FirstName = "Prakash",
                            JoinDate = new DateTime(2025, 9, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Yadav",
                            Phone = "9876543214",
                            Salary = 880000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "farah.ali@xyz.com",
                            FirstName = "Farah",
                            JoinDate = new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Ali",
                            Phone = "9876543215",
                            Salary = 790000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
